apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 9000
  type: NodePort
  selector:
    app: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: web-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: SECRET_KEY
          value: {{ .Values.secret_key }}
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 10
